import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import DemoBadge from "@/components/DemoBadge";
import "./globals.css";

const NAV_LINKS = [
  { href: "/placement?subject=algebra-1", label: "Placement" },
  { href: "/practice", label: "Practice" },
  { href: "/mastery", label: "Mastery" },
  { href: "/personalization-eval", label: "Personalization Evidence" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <DemoBadge />
        <nav className="flex flex-wrap gap-4 border-b border-zinc-200 px-8 py-3 text-sm dark:border-zinc-800">
          {NAV_LINKS.map((link) => (
            <Link key={link.href} href={link.href} className="text-zinc-600 dark:text-zinc-400">
              {link.label}
            </Link>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
